[package]
name = "edmunds"
version = "0.1.0"
authors = ["Yale Cason <yale.cason@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
hyper = "^0.7"
serde = "^0.6"
serde_json = "^0.6"
serde_macros = "^0.6"

[dev-dependencies]
log = "^0.3"